/*
 * File: app/view/CardConfirmationPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.CardConfirmationPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.CardConfirmationPanel',

    config: {
        id: 'CardConfirmationPanel',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Complete Order',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('CardInfoPanel').show({type:'slideIn',direction:'right'});
                            Ext.getCmp('CardConfirmationPanel').hide();
                        },
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        html: '<img src="img/Logo.png" />',
                        padding: 0
                    }
                ]
            },
            {
                xtype: 'fieldset',
                id: 'PRODUCTINFO',
                itemId: 'PRODUCTINFO',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Jersey Size:',
                        labelWidth: '40%',
                        name: 'jerseySize',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Product Price:',
                        labelWidth: '40%',
                        name: 'productPrice',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Jersey Name: ',
                        labelWidth: '40%',
                        name: 'jerseyName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Jersey Number: ',
                        labelWidth: '40%',
                        name: 'jerseyNumber',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'fieldset',
                id: 'CUSTOMERINFO',
                itemId: 'CUSTOMERINFO',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name: ',
                        labelWidth: '40%',
                        name: 'CurName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Address:',
                        labelWidth: '40%',
                        name: 'CurAddress',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'City:',
                        labelWidth: '40%',
                        name: 'CurCity',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'State:',
                        labelWidth: '40%',
                        name: 'CurState',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Zip code:',
                        labelWidth: '40%',
                        name: 'CurZip',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(!Ext.getCmp('alertPanel')){Ext.Viewport.add({xtype: 'alertPanel'});}
                    Ext.getCmp('alertPanel').show({type:'popIn'});
                    /*Ext.Msg.alert('','<div>Thank you Your Order has been processed! Go All Stars!<div>',function(){
                    Ext.getCmp('HomePanel').show({type:'slideIn',direction:'right'});
                    Ext.getCmp('CardConfirmationPanel').hide();
                    });*/
                },
                ui: 'confirm',
                text: 'Submit'
            }
        ]
    }

});