/*
 * File: app/view/CheckOutPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.CheckOutPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.CheckOutPanel',

    config: {
        id: 'CheckOutPanel',
        itemId: 'CheckOutPanel',
        items: [
            {
                xtype: 'component'
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        labelWidth: '40%',
                        placeHolder: 'Required'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Address',
                        labelWidth: '40%',
                        placeHolder: 'Required'
                    },
                    {
                        xtype: 'textfield',
                        label: 'City',
                        labelWidth: '40%',
                        placeHolder: 'Required'
                    },
                    {
                        xtype: 'textfield',
                        label: 'State',
                        labelWidth: '40%',
                        placeHolder: 'Required'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Zip code',
                        labelWidth: '40%',
                        placeHolder: 'Required'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        labelWidth: '40%',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'numberfield',
                        label: 'Phone',
                        labelWidth: '40%',
                        placeHolder: 'Required'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'CheckOut',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            if(!Ext.getCmp('CustomizeFormPanel')){Ext.Viewport.add({xtype: 'CustomizeFormPanel'});}
                            Ext.getCmp('CustomizeFormPanel').show({type:'slideIn',direction:'right'});
                            Ext.getCmp('CheckOutPanel').hide();
                        },
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(!Ext.getCmp('CardInfoPanel')){Ext.Viewport.add({xtype: 'CardInfoPanel'});}
                    Ext.getCmp('CardInfoPanel').show({type:'slideIn',direction:'left'});
                    Ext.getCmp('CheckOutPanel').hide();
                    Ext.getCmp('CardInfoPanel').items.items[3].setTitle(Kiosk4.app.SelectedJersey);
                },
                ui: 'confirm',
                text: 'Proceed'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom'
            }
        ]
    }

});