/*
 * File: app/view/CheckOutPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.CheckOutPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.CheckOutPanel',

    config: {
        id: 'CheckOutPanel',
        itemId: 'CheckOutPanel',
        items: [
            {
                xtype: 'component'
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        placeHolder: 'Name'
                    },
                    {
                        xtype: 'textfield',
                        placeHolder: 'Address'
                    },
                    {
                        xtype: 'textfield',
                        placeHolder: 'City'
                    },
                    {
                        xtype: 'textfield',
                        placeHolder: 'State'
                    },
                    {
                        xtype: 'textfield',
                        placeHolder: 'Zip code'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'CheckOut',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            if(Kiosk4.app.oldPage=='RosterPanel'){
                                if(!Ext.getCmp('RosterPanel')){Ext.Viewport.add({xtype: 'NameAndNumber'});}
                                Ext.getCmp('RosterPanel').show({type:'slideIn',direction:'right'});
                                Ext.getCmp('CheckOutPanel').hide();
                            }else{
                                if(!Ext.getCmp('NameAndNumber')){Ext.Viewport.add({xtype: 'NameAndNumber'});}
                                Ext.getCmp('NameAndNumber').show({type:'slideIn',direction:'right'});
                                Ext.getCmp('CheckOutPanel').hide();

                            }
                        },
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        html: '<img src="img/Logo.png" />',
                        padding: 0
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(!Ext.getCmp('CardInfoPanel')){Ext.Viewport.add({xtype: 'CardInfoPanel'});}
                    Ext.getCmp('CardInfoPanel').show({type:'slideIn',direction:'left'});
                    Ext.getCmp('CheckOutPanel').hide();
                    Ext.getCmp('CardInfoPanel').items.items[3].setTitle(Ext.getCmp('ItemInfo').getData().Name+"("+Ext.getCmp('ItemInfo').getData().amount+")");
                },
                ui: 'confirm',
                text: 'Proceed'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom'
            }
        ]
    }

});