/*
 * File: app/view/conformationPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.conformationPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.conformationPanel',

    config: {
        centered: true,
        height: 350,
        id: 'conformationPanel',
        itemId: 'conformationPanel',
        width: '80%',
        modal: true,
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                cls: 'confTool',
                docked: 'top',
                title: 'Confirmation'
            },
            {
                xtype: 'component',
                id: 'ItemInfo',
                itemId: 'ItemInfo',
                tpl: [
                    '<div align="center">{Name}<br/>{amount}</br><img src="{img}" height="100px"  /><br/>Order {Name} Jersey? </div>'
                ]
            },
            {
                xtype: 'spacer',
                height: 20
            },
            {
                xtype: 'container',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            if(!Ext.getCmp('SizePanel')){Ext.Viewport.add({xtype: 'SizePanel'});}
                            Ext.getCmp('SizePanel').show({type:'slideIn',direction:'left'});
                            Ext.getCmp('HomePanel').hide();
                            Ext.getCmp('conformationPanel').hide();

                            Kiosk4.app.SelectedJersey = Ext.getCmp('ItemInfo').getData().Name+' Jersey';

                            Ext.getCmp('SizePanel').items.items[3].setTitle(Kiosk4.app.SelectedJersey);

                            if(Ext.getCmp('ItemInfo').getData().Name+''=='Replica Home'){
                                Kiosk4.app.classId = 'f43657a1-c83d-499a-ac44-6818d3290395';    
                            }
                            else{
                                Kiosk4.app.classId = 'a88943ae-384f-462b-b4e7-a15f1d35f459';
                            }
                        },
                        ui: 'confirm',
                        width: 60,
                        text: 'Yes'
                    },
                    {
                        xtype: 'spacer',
                        width: 20
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('conformationPanel').hide();
                        },
                        ui: 'decline',
                        width: 60,
                        text: 'No'
                    }
                ]
            }
        ]
    }

});