/*
 * File: app/view/CustomizePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.CustomizePanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.CustomizePanel',

    config: {
        id: 'CustomizePanel',
        itemId: 'CustomizePanel',
        items: [
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(!Ext.getCmp('NameAndNumber')){Ext.Viewport.add({xtype: 'NameAndNumber'});}
                    Ext.getCmp('NameAndNumber').show({type:'slideIn',direction:'left'});
                    Ext.getCmp('CustomizePanel').hide();
                    Ext.getCmp('NameAndNumber').items.items[4].setTitle(Ext.getCmp('ItemInfo').getData().Name);
                },
                ui: 'confirm',
                text: 'Custom name and number'
            },
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(!Ext.getCmp('RosterPanel')){Ext.Viewport.add({xtype: 'RosterPanel'});}
                    Ext.getCmp('RosterPanel').show({type:'slideIn',direction:'left'});
                    Ext.getCmp('CustomizePanel').hide();
                    Ext.getCmp('RosterPanel').items.items[1].setTitle(Ext.getCmp('ItemInfo').getData().Name);
                },
                ui: 'confirm',
                text: 'Choose from team roster'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Customize Options',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('SizePanel').show({type:'slideIn',direction:'right'});
                            Ext.getCmp('CustomizePanel').hide();
                        },
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom'
            }
        ]
    }

});