/*
 * File: app/view/CustomizeFormPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.CustomizeFormPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.CustomizeFormPanel',

    config: {
        id: 'CustomizeFormPanel',
        itemId: 'CustomizeFormPanel',
        scrollable: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Customize',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            if(Kiosk4.app.oldPage=='RosterPanel'){
                                if(!Ext.getCmp('RosterPanel')){Ext.Viewport.add({xtype: 'NameAndNumber'});}
                                Ext.getCmp('RosterPanel').show({type:'slideIn',direction:'right'});
                                Ext.getCmp('CustomizeFormPanel').hide();
                            }else{
                                if(!Ext.getCmp('NameAndNumber')){Ext.Viewport.add({xtype: 'NameAndNumber'});}
                                Ext.getCmp('NameAndNumber').show({type:'slideIn',direction:'right'});
                                Ext.getCmp('CustomizeFormPanel').hide();

                            }
                        },
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom'
            },
            {
                xtype: 'panel',
                html: '<div id="canvas_container"></div>',
                itemId: 'myfieldset8',
                margin: 20
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(!Ext.getCmp('CheckOutPanel')){Ext.Viewport.add({xtype: 'CheckOutPanel'});}
                    Ext.getCmp('CheckOutPanel').show({type:'slideIn',direction:'left'});
                    Ext.getCmp('CustomizeFormPanel').hide();
                    Ext.getCmp('CheckOutPanel').items.items[4].setTitle(Kiosk4.app.SelectedJersey);
                },
                margin: '0 10 0 10',
                ui: 'confirm',
                text: 'Check Out'
            }
        ],
        listeners: [
            {
                fn: 'onCustomizeFormPanelShow',
                event: 'show'
            }
        ]
    },

    onCustomizeFormPanelShow: function(component, eOpts) {
        var task = new Ext.util.DelayedTask(function() {
            drawTShirt(Kiosk4.app.jerseyName, Kiosk4.app.jerseyNumber);
        });

        task.delay(500);

        Ext.getCmp('CustomizeFormPanel').mask({
            message:'Please wait...',
        xtype: 'loadmask'});
    }

});