/*
 * File: app/view/SizePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.SizePanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.SizePanel',

    config: {
        id: 'SizePanel',
        itemId: 'SizePanel',
        items: [
            {
                xtype: 'fieldset',
                cls: 'SizeBox',
                title: 'Adult',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            align: 'start',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'Medium'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'Large'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        height: 20
                    },
                    {
                        xtype: 'container',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'X Large'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'XX Large'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                cls: 'SizeBox',
                title: 'Youth',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            align: 'start',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'Medium'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'Large'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        height: 20
                    },
                    {
                        xtype: 'container',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'X Large'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            },
                            {
                                xtype: 'button',
                                cls: 'sizeBut',
                                ui: 'confirm',
                                text: 'XX Large'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Choose Size',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('HomePanel').show({type:'slideIn',direction:'right'});
                            Ext.getCmp('SizePanel').hide();
                        },
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        html: '<img src="img/Logo.png" />',
                        padding: 0
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom'
            }
        ]
    }

});