/*
 * File: app/view/Spalshscreen.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.view.Spalshscreen', {
    extend: 'Ext.form.Panel',
    alias: 'widget.Spalshscreen',

    config: {
        id: 'Spalshscreen',
        itemId: 'Spalshscreen',
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'container',
                ui: '',
                width: 288,
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'component',
                        height: 330,
                        html: '<div id="imgSplaceScreen">  <div align="center" style="padding-top: 70px;"> <span ><img class="loaderimagecontainer" src="images.jpg" /> </span><div>Order your custom Jersey!</div></div> 	 <div id="appLoadingIndicator">             <div class="loadertextheader1"></div>              <div class="loadertextheader2"></div>              <div class="loaderimg" style="margin-left: -40px;" ><img src="modal-loader.gif" /></div>     </div>   <div>',
                        width: '90%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            if(!Ext.getCmp('HomePanel')){Ext.Viewport.add({xtype: 'HomePanel'});}
                            Ext.getCmp('HomePanel').show({type:'slideIn',direction:'left'});
                            Ext.getCmp('Spalshscreen').hide();
                            clearInterval(Kiosk4.app.spalShScreen);
                        },
                        ui: 'confirm',
                        text: 'Click to Continue'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onSpalshscreenPainted',
                event: 'painted'
            }
        ]
    },

    onSpalshscreenPainted: function(element, eOpts) {
        Kiosk4.app.spalShScreen=setInterval(function(){
            if(!Ext.getCmp('HomePanel')){Ext.Viewport.add({xtype: 'HomePanel'});}
            Ext.getCmp('HomePanel').show({type:'slideIn',direction:'left'});
            Ext.getCmp('Spalshscreen').hide();
        },5000);
    }

});