/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    viewport: {
        autoMaximize: true
    },

    views: [
        'NameAndNumber',
        'SizePanel',
        'CustomizePanel',
        'RosterPanel',
        'CheckOutPanel',
        'CardInfoPanel',
        'HomePanel',
        'conformationPanel',
        'CardConfirmationPanel',
        'Spalshscreen',
        'alertPanel',
        'CustomizeFormPanel'
    ],
    controllers: [
        'mainCrl'
    ],
    name: 'Kiosk4',

    launch: function() {

        Ext.create('Kiosk4.view.Spalshscreen', {fullscreen: true});
    }

});
