/*
 * File: app/controller/mainCrl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiosk4.controller.mainCrl', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button[cls=HomeBut]": {
                release: 'onButtonRelease'
            },
            "button[cls=AdultsizeBut]": {
                release: 'onButtonRelease1'
            },
            "button[cls=HomeCls]": {
                release: 'onButtonRelease2'
            },
            "button[cls=YouthsizeBut]": {
                release: 'onButtonRelease3'
            }
        }
    },

    onButtonRelease: function(button, e, eOpts) {
        if(!Ext.getCmp('conformationPanel')){Ext.Viewport.add({xtype: 'conformationPanel'});}
        Ext.getCmp('conformationPanel').show({type:'popIn',direction:'left'});
        if(button.config.no==1){
            data={Name:"Replica Home",amount:'$100.00 - $150.00',img:"img/Dallas_3.jpg"};
        }else if(button.config.no==2){
            data={Name:"Replica Away",amount:'$100.00 - $150.00',img:"img/Dallas_4.jpg"};
        }
        Ext.getCmp('ItemInfo').setData(data);
    },

    onButtonRelease1: function(button, e, eOpts) {
        Kiosk4.app.size='$150';
        if(!Ext.getCmp('CustomizePanel')){Ext.Viewport.add({xtype: 'CustomizePanel'});}
        Ext.getCmp('CustomizePanel').show({type:'slideIn',direction:'left'});
        Ext.getCmp('SizePanel').hide();
        Ext.getCmp('CustomizePanel').items.items[5].setTitle(Kiosk4.app.SelectedJersey);

        Kiosk4.app.JerseySize = button.getText() + ' (Adult)';
    },

    onButtonRelease2: function(button, e, eOpts) {
        if(!Ext.getCmp('conformationPanel')){Ext.Viewport.add({xtype: 'conformationPanel'});}
        Ext.getCmp('conformationPanel').show({type:'popIn',direction:'left'});
        if(button.config.no==1){
            data={Name:"Replica Home",amount:'$100.00 - $150.00',img:"img/img4.png"};
        }else if(button.config.no==2){
            data={Name:"Replica Away",amount:'$100.00 - $150.00',img:"img/img5.png"};
        }	
        Ext.getCmp('ItemInfo').setData(data);
    },

    onButtonRelease3: function(button, e, eOpts) {
        Kiosk4.app.size='$100';
        if(!Ext.getCmp('CustomizePanel')){Ext.Viewport.add({xtype: 'CustomizePanel'});}
        Ext.getCmp('CustomizePanel').show({type:'slideIn',direction:'left'});
        Ext.getCmp('SizePanel').hide();
        Ext.getCmp('CustomizePanel').items.items[5].setTitle(Kiosk4.app.SelectedJersey);

        Kiosk4.app.JerseySize = button.getText() + ' (Youth)';
    }

});